services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app